services:

  redis:
    image: redis:7-alpine
    container_name: docflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    container_name: docflow-postgres
    environment:
      POSTGRES_USER: docflow
      POSTGRES_PASSWORD: docflow
      POSTGRES_DB: docflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: